### ISSUE TITLE
Please Add streamdeck-octodeck

### ISSUE THREAD

**Issue by cpeuschel** [madmatt/streamdeck-plugins#35]
Plugin name: OctoDeck
Plugin description: This plugin shows your 3D-Printer completion state in percent on your StreamDeck  (OctoPrint required)
Supports Windows (Yes/No): Yes
Supports Mac (Yes/No): Not testet
Author name: Christian Peuschel
Homepage URL: https://github.com/cpeuschel
Plugin download link: https://github.com/cpeuschel/streamdeck-octodeck/releases

**Comment by BarRaider** [comment]
Looks like you have a small bug in your code. 
https://github.com/cpeuschel/streamdeck-octodeck/blob/4c854a5afe9932662fe4567fab1d486e9f4b4c17/com.cpeuschel.octodeck.sdPlugin/main.html#L55

You should save this into a variable and stop it with the OnWillDisappear event, otherwise you'll cause a memory leak

**Comment by cpeuschel** [comment]
Hello @BarRaider, 
thank you for your code review. I have modified my code. Here is the [PR](https://github.com/cpeuschel/streamdeck-octodeck/pull/1/). Do you think its ok now?

**Comment by BarRaider** [comment]
I think you may want to set autoUpdate back to null after calling clearInterval but it may be fine like this too. Eother way, yeah, it solves the issue I was referring to.
I will push the update to add your plugin later today

**Comment by cpeuschel** [comment]
Thank you very much.
